title:  # your name (or website title) here
logo:  # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href ="file:///C|/Desktop\Github_Resume.pdf"> Resume </a>
  <br><br>
  <a href="https://www.linkedin.com/in/example/"> Coursework </a>
  <br><br>
  <a href="https://www.linkedin.com/in/example/"> LinkedIn </a>
  <br><br>
  <a href="https://www.linkedin.com/in/example/"> GitHub </a>


theme: jekyll-theme-minimal
