title: Rachel Chung # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Resume
  <br><br>
  <a href="https://www.linkedin.com/in/example/"> LinkedIn </a>
  <br><br>
  <a href="https://www.linkedin.com/in/example/"> GitHub </a>
  <br><br>
  <a href="https://www.linkedin.com/in/example/"> Tableau </a>


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
