title:  # your name (or website title) here
logo:  # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <img src="images/profile.png?raw=true"/>
  <br><br>
  <a href ="file:///C|/Desktop\Github_Resume.pdf"> Email </a>
  <br><br>
  <a href="https://www.linkedin.com/in/example/"> Resume </a>
  <br><br>
  <a href="https://www.linkedin.com/in/example/"> LinkedIn </a>
  <br><br>
  <a href="https://www.linkedin.com/in/example/"> GitHub </a>


theme: jekyll-theme-minimal
